interfaces:
  eth0:
    method: "static"
    ipv4: "192.168.0.1/24"
    gateway_ipv4: "192.168.0.1"
    vlan-raw-device: "eth0"
  eth0.1:
    method: "static"
    ipv4: "192.168.1.1/24"
    gateway_ipv4: "192.168.10.1"
    vlan-raw-device: "eth0"
